### ISSUE TITLE
Not able to Install and use

### ISSUE THREAD

**Issue by sameeryel** [JulienHeijmans/quicksnap#11]
![image](https://user-images.githubusercontent.com/12401987/195851777-7a71aded-d40a-478c-b72f-c48148680101.png)

I get this error after installing and trying to activate the addon

**Comment by JulienHeijmans** [comment]
Hi!
Could you copy paste here the last few lines in the console before the error happens? (Open the system console via the menu Window > Toggle System Console)

**Comment by JulienHeijmans** [comment]
Oh, ok, strange issue, I will look into it. But, I am happy that you got around your issue!

> Also, it would be better to have it click once to move around and then click again to fix position instead of click and dragging around.

Yes, someone else requested that, I will try to do it when I have some time. There are some other features I am finishing first ([snapping from/to edge center and face center](https://github.com/JulienHeijmans/quicksnap/tree/pie-menu), then a way to ignore all modifiers or all modifiers except mirror), then I will do that.

Thank you for posting here!

**Comment by JulienHeijmans** [comment]
Ah I understand now why you had the issue, I will try to find a way to fix it, so people can use these zip files too, thanks for reporting!

**Comment by Siya-33** [comment]
same problem after installing

**Comment by JulienHeijmans** [comment]
Hey, you should install following the instructions in the Readme (here https://github.com/JulienHeijmans/quicksnap)

The problem comes from the name of the folder in the zip file, it is containing the dots "." from the version number, and blender does not support that. I can't control it as they are made automatically by github. In the future I will name the releases tags differently.
In the meantime, you should use this link to download the latest version :

https://github.com/JulienHeijmans/quicksnap/archive/refs/heads/main.zip

**Comment by Siya-33** [comment]
Thanks for your great contribution in Blender!

**Comment by JulienHeijmans** [comment]
The format of the github tag of the [new version](https://github.com/JulienHeijmans/quicksnap/releases/tag/1_3_0) is now using underscore instead of dots, which should avoid those kinds of issue from now on.

Thank you again for reporting the issue!
