### ISSUE TITLE
Pie Menu Inaccessible

### ISSUE THREAD

**Issue by jordiart3d** [JulienHeijmans/quicksnap#29]
![imagen](https://user-images.githubusercontent.com/90904598/197152469-c738fed7-f36b-4bb9-9dc6-068ee3941641.png)
Even forcing it manually on the keymap, i can´t use the pie menu.
Shortcut doesn´t work, press the same key as the operator ( hard to find on the documentation ) doesn´t work either
addon version 1.3.3
blender version 3.4 alpha

**Comment by JulienHeijmans** [comment]
Hi!

So, you are not supposed to add another keymap, just use the existing one, the one displayed in the addon preferences.
The operator will open the pie menu when the same keymap is pressed. So there is no need to use two different keymaps for the tool.

Anyway... When I try to bind any action to Ctrl+F1 in the keymap preferences, the input just does not work. I think that it is just a combination that you cannot use in Blender. Did you try with another combination of keys?

Here a small video showing that Ctrl+F1 is just not picked by blender (That seem to be the case for any keymap), same for Ctrl+F3, for some reason. But if I try with Shift+F1 for example, blender picks the hotkey properly, and the pie menu works without issue.
https://user-images.githubusercontent.com/35562774/197157227-8786ed34-82f1-44b7-8fd0-394e20541ee6.mp4

> press the same key as the operator ( **hard to find on the documentation** ) 

Hard to find, really? It is written twice in the readme page, and also clearly listed in the addon preferences.
<img width="397" alt="blender_7P66GtDpgg" src="https://user-images.githubusercontent.com/35562774/197158071-8674e7f0-41fa-4af9-b07a-85e8badf56ad.png">
How else do you think it should be presented?

**Comment by jordiart3d** [comment]
The same shorcut doesn´t trigger the pie menu, it only trigger the operator for me
this isnt working in 3.4 alpha, i´ve not tried on earlier blender version

**Comment by JulienHeijmans** [comment]
Alright, I will give it a try with 3.4a and see if there is an issue there.
What key combination did you use, so I can try with the same?

**Comment by jordiart3d** [comment]
CTRL + SHIFT + A works triggering the operator

**Comment by jordiart3d** [comment]
Sometimes i´ve issues with other pie menus, it can be the monitor DPI stuff, can you share your settings for them?
this are mines : 
![imagen](https://user-images.githubusercontent.com/90904598/197168046-7960f64c-4b2d-4bef-a0f7-cae51daee8eb.png)

**Comment by JulienHeijmans** [comment]
I have the exact same PIE settings as you in Blender. So that should not be the problem.

> you´re supposed to do the gesture for the pie menu just after the operator is active right?

Yes, but you don't have to do it straight away, you just have to keep the hotkey pressed, move the mouse cursor where you want and then release the hotkey.

So, I tried with your hotkey (Ctrl+Shift+A), on blender 3.4alpha, and had no issue.
I also tried creating a new keymap like you, calling the `wm.call_menu_pie` operator with `VIEW3D_MT_PIE_quicksnap` as the pie name, and the pie menu did show up. So, it looks like it's the pie menu itself the issue and not the key binding.

Just to check, could you download the latest version on [github here](https://github.com/JulienHeijmans/quicksnap) (Instructions in the readme), and do the following:
- Start the tool using your keymap (Have a single box selected)
- Press CTRL+SHIFT+TAB once, you should see a notification at the bottom of the window saying that it is changing the debug mode.
- Press escape to terminate the tool
- Start the tool again, and hit the same keymap again (which normally opens the pie menu)
- Then look in the logs (Menu Window - Toggle System Console)

You should see something like this:
```
[INFO] 2022-10-21 15:34:09,502 Detecting current hotkey
[INFO] 2022-10-21 15:34:09,502 Tool hotkey stored: Ctrl:1 - Shift:1 - Alt:0 - Key:A
[INFO] 2022-10-21 15:34:09,788 Pie menu called.
```
Tell me if you do, or if you see any error.
If you see `Pie menu called`, then the issue is indeed with the pie menu itself, and to be honest I do not know what could be the issue, it really is a super basic menu, I am not doing anything unusual in the code there.

**Comment by jordiart3d** [comment]
Really sorry for the troubleshooting man, i´ve finally found what was causing my issue, it wasn´t the addon itself!
My workspace was configured to filter the addons, and i forgot to activate QuickSnap there... now the pie menu works too!
Thanks for the patience, very good addon indeed ;)

**Comment by JulienHeijmans** [comment]
Haha, alright no problem, good to hear that the problem is solved!
Have a nice weekend!

I will set this issue as solved.
