### ISSUE TITLE
error in edit mode Ver3.3.1

### ISSUE THREAD

**Issue by tewadaa** [JulienHeijmans/quicksnap#7]
I get an error when trying to snap in edit mode.

Any solution?

![image](https://user-images.githubusercontent.com/115567978/195122776-c0535e0d-8e16-45c2-8ecc-68cdefb4f512.png)

**Comment by JulienHeijmans** [comment]
Hi,

This bug should be fixed in version 1.2.1 of this addon.

To update the Add-On:
- In the Add-on preferences, scroll down, click on "Check now for QuickSnap update"
- Then "Update now to (1, 2, 3)"

Here is a video of how to update: (You need to click the play icon in the top right corner)
![quicksnap-update](https://user-images.githubusercontent.com/35562774/195124130-47a3607a-ae97-44f3-bbed-b65a5ef341e9.gif)


Please post a reply here to confirm that the issue has been fixed for you.

**Comment by tewadaa** [comment]
Thanks for your prompt reply!

I just bought it from BlenderMarket, so the version should be the latest.

![image](https://user-images.githubusercontent.com/115567978/195125643-32559354-1460-4cae-8c48-ad60c9e34cfe.png)

**Comment by JulienHeijmans** [comment]
Oh, yes indeed I can see where is the issue.
Sorry, I read your error message too quickly. Hang on, I should have a fix very soon.

**Comment by JulienHeijmans** [comment]
Could you try updating the tool now and see if it works ? Version 1.2.4.

**Comment by tewadaa** [comment]
I was able to move it even in edit mode!

A big thank you for making them great.

**Comment by JulienHeijmans** [comment]
Super, thank you again for reporting the issue and making the tool better!
